### ISSUE TITLE
Formato de la request en AddMachineRouter

### ISSUE THREAD

**Issue by dnchia** [VendingOnTime/server-vot#36]
AddMachineRouter debería estar preparado para aceptar un JSON en formato:

{
location: String, 
type: String (correspondiente a la enumeración del servidor), 
state: String (correspondiente a la enumeración del servidor), 
description: String
}

Y como mínimo estar preparada para añadir al técnico en un futuro, de momento no se está añadiendo en la petición, aunque sí que se le pide al usuario.

**Comment by albertogonper** [comment]
Arreglado, ahora está homogéneo con respecto a la representación de máquina en el modelo de respuesta.

Ello incluye que location es un objeto compuesto con un atributo name de tipo string

La cosa quedaría así al final:
```
{
    location: {
        name: String
    },
    type: String (correspondiente a la enumeración del servidor),
    state: String (correspondiente a la enumeración del servidor),
    description: String
}
```
